/* EvoluaFit - Conta V3 */
(function(){
  if(window.__evoluaAccountV3)return;window.__evoluaAccountV3=true;
  const $=id=>document.getElementById(id);
  function estilos(){if($("evolua-account-v3-style"))return;const s=document.createElement("style");s.id="evolua-account-v3-style";s.textContent='.cloud-recovery-v3{width:100%;margin-top:2px;padding:9px 10px;border:0;border-radius:11px;background:transparent;color:#2563eb;font-size:11px;font-weight:800;text-align:center}.cloud-account-extra-v3{margin-top:10px;padding-top:10px;border-top:1px solid var(--border-color)}.cloud-account-extra-v3 button{width:100%;min-height:38px;padding:8px 10px;border-radius:11px;background:rgba(37,99,235,.08);color:#2563eb;border:1px solid rgba(37,99,235,.12);font-size:11px;font-weight:850}';document.head.appendChild(s)}
  function status(msg,tipo){const el=$("cloudStatusEvoluaFit");if(!el)return;el.textContent=msg;el.className=`cloud-status-evoluafit ${tipo||""}`.trim()}
  async function recuperar(){const fb=window.firebase;if(!fb||!fb.auth){status("Firebase ainda não está pronto. Tente novamente em alguns segundos.","erro");return}const auth=fb.auth(),u=auth.currentUser,c=$("cloudEmailEvoluaFit"),email=String((u&&u.email)||(c&&c.value)||"").trim();if(!email){status("Digite seu e-mail para receber o link de recuperação.","erro");return}try{status("Enviando link de recuperação...","");await auth.sendPasswordResetEmail(email);status("Link para redefinir a senha enviado para seu e-mail.","ok")}catch(e){const code=e&&e.code;status(code==="auth/invalid-email"?"O e-mail informado é inválido.":code==="auth/user-not-found"?"Não encontrei uma conta com esse e-mail.":"Não consegui enviar o link agora. Verifique a conexão e tente novamente.","erro")}}
  function garantir(){estilos();const login=$("cloudLoginAreaEvoluaFit");if(login&&!$("btnCloudRecoveryV3")){const b=document.createElement("button");b.id="btnCloudRecoveryV3";b.type="button";b.className="cloud-recovery-v3";b.textContent="Esqueci minha senha";b.addEventListener("click",recuperar);login.appendChild(b)}const logado=$("cloudLogadoAreaEvoluaFit");if(logado&&!$("cloudAccountExtraV3")){const x=document.createElement("div");x.id="cloudAccountExtraV3";x.className="cloud-account-extra-v3";x.innerHTML='<button type="button" id="btnCloudResetLoggedV3"><i class="bi bi-key"></i> Enviar link para redefinir senha</button>';logado.appendChild(x);$("btnCloudResetLoggedV3").addEventListener("click",recuperar)}}
  document.addEventListener("DOMContentLoaded",garantir);if(document.readyState!=="loading")setTimeout(garantir,0);setInterval(garantir,1800);
})();
