/* EvoluaFit Experience V6 */
(function(){
  if(window.__evoluaExperienceV6)return;window.__evoluaExperienceV6=true;
  var API="https://luma-gemini-api.onrender.com", MEALS=["cafe","almoco","jantar","ceia"], LABELS={cafe:"Café da manhã",almoco:"Almoço",jantar:"Jantar",ceia:"Ceia"};
  var weightChart=null, weightDays=30, calCursor=new Date(), selectedDate=iso(new Date()), oldTrocar=null, observer=null;
  function $(id){return document.getElementById(id)}
  function j(key,f){try{var v=JSON.parse(localStorage.getItem(key)||"null");return v==null?f:v}catch(_){return f}}
  function n(v){var x=Number(String(v==null?"":v).replace(",","."));return Number.isFinite(x)?x:null}
  function iso(d){d=d instanceof Date?d:new Date(d);return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
  function pd(v){if(!v)return null;var s=String(v),m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})/);if(m)return new Date(+m[3],+m[2]-1,+m[1]);m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return new Date(+m[1],+m[2]-1,+m[3]);var d=new Date(v);return isNaN(d)?null:d}
  function itemDate(x){if(!x)return null;var a=[x.data,x.date,x.dataISO,x.dataHora,x.timestamp,x.criadoEm,x.id];for(var i=0;i<a.length;i++){var d=pd(a[i]);if(d)return d}return null}
  function wval(x){if(!x)return null;var a=[x.peso,x.weight,x.valor,x.value,x.kg];for(var i=0;i<a.length;i++){var v=n(a[i]);if(v!=null&&v>20&&v<400)return v}return null}
  function esc(s){return String(s==null?"":s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
  function dur(v){v=n(v);if(v==null||v<=0)return "—";v=Math.round(v);var h=Math.floor(v/60),m=v%60;return h?h+"h "+String(m).padStart(2,"0")+"m":m+" min"}
  function weights(){var a=j("historicoPeso",[]);return Array.isArray(a)?a.map(function(x){return{d:itemDate(x),v:wval(x)}}).filter(function(x){return x.d&&x.v!=null}).sort(function(a,b){return a.d-b.d}):[]}
  function styles(){if($("v6style"))return;var s=document.createElement("style");s.id="v6style";s.textContent=
  "body.evolua-v6 .app-container{padding-bottom:104px!important}body.evolua-v6 #aba-dashboard>*:not(header):not(#v6home){display:none!important}body.evolua-v6 #aba-dashboard header>div:last-child{display:none!important}"+
  ".v6box{margin:0 0 14px;padding:15px;border:1px solid var(--border-color);border-radius:20px;background:var(--card-bg);box-shadow:0 10px 28px rgba(15,23,42,.055);animation:v6up .28s ease both}.v6hero{padding:18px;border-radius:24px;background:linear-gradient(140deg,rgba(37,99,235,.18),rgba(139,92,246,.09),rgba(16,185,129,.06));border:1px solid rgba(96,165,250,.22)}"+
  ".v6top{display:flex;justify-content:space-between;gap:12px}.v6ey{font-size:9px;text-transform:uppercase;color:var(--text-muted);font-weight:900}.v6w{font-size:39px;font-weight:950;line-height:1;margin-top:6px}.v6w small{font-size:15px;color:var(--text-muted)}.v6goal{text-align:right}.v6goal strong{display:block;font-size:18px;margin-top:5px}.v6goal small{font-size:9px;color:var(--text-muted)}"+
  ".v6bar{height:9px;margin-top:17px;border-radius:999px;background:rgba(148,163,184,.18);overflow:hidden}.v6bar i{display:block;height:100%;background:linear-gradient(90deg,#38bdf8,#2563eb,#8b5cf6);transition:width .5s}.v6foot{display:flex;justify-content:space-between;margin-top:7px;font-size:9.5px;color:var(--text-muted);font-weight:750}"+
  ".v6title{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:11px}.v6title strong{font-size:15px;font-weight:950}.v6title small{font-size:9px;color:var(--text-muted)}.v6grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v6stat{padding:12px;border:1px solid var(--border-color);border-radius:16px;background:rgba(148,163,184,.04)}.v6stat .k{font-size:9px;text-transform:uppercase;color:var(--text-muted);font-weight:850}.v6stat .v{font-size:19px;font-weight:950;margin-top:4px}.v6stat .s{font-size:9px;color:var(--text-muted);margin-top:3px}"+
  ".v6luma{background:linear-gradient(145deg,rgba(124,58,237,.12),rgba(37,99,235,.07));border-color:rgba(124,58,237,.16)}.v6lh{display:flex;align-items:center;gap:10px;margin-bottom:9px}.v6orb{width:38px;height:38px;border-radius:14px;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,#7c3aed,#2563eb);color:white}.v6lt{font-size:13px;font-weight:950}.v6ls{font-size:9px;color:var(--text-muted)}.v6text{font-size:12px;line-height:1.55;font-weight:650}.v6actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:11px}.v6soft{padding:9px 11px;border-radius:12px;border:1px solid var(--border-color);background:rgba(148,163,184,.06);color:var(--text-main);font-size:10px;font-weight:850}.v6soft.primary{background:#2563eb;color:#fff;border-color:#2563eb}"+
  ".v6quick{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.v6quick button{padding:10px 4px;border-radius:15px;border:1px solid var(--border-color);background:rgba(148,163,184,.05);color:var(--text-main);font-size:9px;font-weight:850}.v6quick i{display:block;margin:0 0 5px;font-size:18px;color:#2563eb}.v6periods{display:flex;gap:4px}.v6period{padding:6px 7px;border-radius:9px;border:1px solid var(--border-color);background:transparent;color:var(--text-muted);font-size:8.5px;font-weight:900}.v6period.active{background:#2563eb;color:white;border-color:#2563eb}.v6chart{height:190px}.v6chart canvas{width:100%!important;height:190px!important}"+
  "body.evolua-v6 .floating-main{display:none!important}body.evolua-v6 .floating-nav{bottom:calc(10px + env(safe-area-inset-bottom));pointer-events:auto;padding:0 10px}body.evolua-v6 .floating-menu{position:relative!important;bottom:auto!important;width:min(100%,520px)!important;display:grid!important;grid-template-columns:repeat(5,1fr)!important;gap:3px!important;padding:6px!important;border-radius:22px!important;opacity:1!important;transform:none!important;pointer-events:auto!important}body.evolua-v6 .floating-item{opacity:1!important;transform:none!important;width:100%!important;height:58px!important;min-width:0!important;padding:5px 2px!important;border-radius:16px!important}body.evolua-v6 .floating-item i{font-size:18px!important;margin:0!important}body.evolua-v6 .floating-item span{font-size:9px!important}body.evolua-v6 .floating-item.active{background:rgba(37,99,235,.13)!important;color:#2563eb!important}"+
  "#aba-perfil-v6{display:none}.v6settings{display:flex;flex-direction:column;gap:8px}.v6settings button{width:100%;display:flex;justify-content:space-between;align-items:center;padding:12px 13px;border-radius:15px;border:1px solid var(--border-color);background:rgba(148,163,184,.04);color:var(--text-main);font-size:11px;font-weight:850;text-align:left}.v6settings i{color:#2563eb;font-size:17px}.v6settings small{color:var(--text-muted);font-size:9px}.v6healthhead{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}#v6HealthHost #healthConnectCard{margin:0!important}#v6HealthHost #healthConnectCard .hc-head,#v6HealthHost #healthConnectCard .hc-actions,#v6HealthHost #healthConnectCard .hc-foot,#v6HealthHost #healthConnectCard .hc-diagnostic{display:none!important}#v6HealthHost #healthConnectCard.tech .hc-actions,#v6HealthHost #healthConnectCard.tech .hc-foot{display:flex!important}#v6HealthHost #healthConnectCard.tech .hc-foot{display:block!important}.v6tech{width:100%;margin-top:8px;padding:9px;border-radius:12px;border:1px solid var(--border-color);background:transparent;color:var(--text-muted);font-size:10px;font-weight:850}"+
  ".v6cal{margin-bottom:14px;padding:14px;border-radius:19px;border:1px solid var(--border-color);background:var(--card-bg)}.v6calh{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.v6calnav{display:flex;gap:5px}.v6calnav button{width:34px;height:34px;padding:0;border-radius:10px;background:rgba(148,163,184,.08);color:var(--text-main)}.v6week,.v6days{display:grid;grid-template-columns:repeat(7,1fr);gap:4px}.v6week span{text-align:center;font-size:8px;color:var(--text-muted);font-weight:850}.v6day{aspect-ratio:1;border:0;border-radius:10px;padding:0;background:transparent;color:var(--text-main);font-size:10px;font-weight:800;position:relative}.v6day.other{opacity:.28}.v6day.today{box-shadow:inset 0 0 0 1px #2563eb}.v6day.sel{background:#2563eb;color:#fff}.v6day.has:after{content:'';position:absolute;bottom:4px;left:50%;width:4px;height:4px;border-radius:50%;background:#10b981;transform:translateX(-50%)}.v6summary{margin-top:12px;padding-top:12px;border-top:1px solid var(--border-color)}.v6sumgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.v6sum{padding:8px;border-radius:11px;border:1px solid var(--border-color);background:rgba(148,163,184,.04)}.v6sum span{display:block;font-size:7px;color:var(--text-muted);text-transform:uppercase;font-weight:850}.v6sum strong{display:block;font-size:11px;margin-top:4px}"+
  ".v6meal{margin-top:9px;padding:10px;border-radius:14px;border:1px solid rgba(249,115,22,.18);background:rgba(249,115,22,.055)}.v6macros{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:7px}.v6macro{text-align:center;padding:6px;border-radius:9px;border:1px solid var(--border-color);background:var(--card-bg)}.v6macro span{display:block;font-size:7px;color:var(--text-muted);text-transform:uppercase}.v6macro strong{font-size:10px}.v6meal button{float:right;margin-top:7px;padding:6px 8px;border-radius:9px;background:rgba(249,115,22,.1);color:#ea580c;border:1px solid rgba(249,115,22,.2);font-size:8.5px;font-weight:850}"+
  ".v6sheet{position:fixed;inset:0;z-index:100000;display:flex;align-items:flex-end;justify-content:center;background:rgba(2,6,23,.55);padding:12px}.v6sheetin{width:min(100%,540px);max-height:88vh;overflow:auto;padding:14px;border-radius:24px 24px 18px 18px;background:var(--card-bg);border:1px solid var(--border-color)}.v6sheeth{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.v6close{width:36px;height:36px;padding:0;border-radius:10px;background:rgba(148,163,184,.08);color:var(--text-main)}.v6edit{display:grid;grid-template-columns:1.5fr .85fr .6fr;gap:5px;margin-bottom:6px}.v6edit input{padding:9px!important;font-size:11px!important}.v6form{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v6form label{font-size:9px;color:var(--text-muted);font-weight:800}.v6save{width:100%;margin-top:11px}.v6lq{display:grid;grid-template-columns:1fr 1fr;gap:7px}.v6lq button{display:flex;align-items:center;gap:8px;min-height:44px;padding:9px;border-radius:13px;border:1px solid rgba(124,58,237,.15);background:rgba(124,58,237,.07);color:var(--text-main);font-size:10px;font-weight:850;text-align:left}.v6lq i{color:#7c3aed;font-size:16px}"+
  "body.evolua-v6 #aba-alimentacao .meal-card{border-left:3px solid rgba(249,115,22,.7)}@keyframes v6up{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:none}}@media(max-width:390px){.v6quick{grid-template-columns:1fr 1fr}.v6sumgrid{grid-template-columns:1fr 1fr}}";
    document.head.appendChild(s)
  }
  function home(){
    var a=$("aba-dashboard");if(!a||$("v6home"))return;var h=a.querySelector("header"),x=document.createElement("div");x.id="v6home";x.innerHTML=
    '<section class="v6hero"><div class="v6top"><div><div class="v6ey">Peso atual</div><div id="v6Weight" class="v6w">— <small>kg</small></div></div><div class="v6goal"><small>Meta</small><strong id="v6Goal">— kg</strong><small id="v6Remain">Defina sua meta</small></div></div><div class="v6bar"><i id="v6Prog" style="width:0%"></i></div><div class="v6foot"><span id="v6Start">Início —</span><span id="v6Lost">Evolução —</span></div></section>'+
    '<section class="v6box"><div class="v6title"><strong>Seu dia</strong><small id="v6Date"></small></div><div class="v6grid"><div class="v6stat"><div class="k">Calorias</div><div id="v6Kcal" class="v">—</div><div class="s">Diário</div></div><div class="v6stat"><div class="k">Passos</div><div id="v6Steps" class="v">—</div><div class="s">Atividade</div></div><div class="v6stat"><div class="k">Sono</div><div id="v6Sleep" class="v">—</div><div class="s">Último registro</div></div><div class="v6stat"><div class="k">FC média</div><div id="v6Heart" class="v">—</div><div class="s">Hoje</div></div></div></section>'+
    '<section class="v6box v6luma"><div class="v6lh"><div class="v6orb"><i class="bi bi-stars"></i></div><div><div class="v6lt">Luma do dia</div><div class="v6ls">Usa somente dados que existem</div></div></div><div id="v6Luma" class="v6text">Organizando seu dia…</div><div class="v6actions"><button id="v6LumaRefresh" class="v6soft primary">Atualizar resumo</button><button id="v6LumaOpen" class="v6soft">Abrir Luma</button></div></section>'+
    '<section class="v6box"><div class="v6title"><strong>Ações rápidas</strong><small>Um toque</small></div><div class="v6quick"><button data-a="weight"><i class="bi bi-speedometer2"></i>Peso</button><button data-a="meal"><i class="bi bi-camera"></i>Refeição</button><button data-a="workout"><i class="bi bi-activity"></i>Treino</button><button data-a="health"><i class="bi bi-heart-pulse"></i>Saúde</button></div></section>'+
    '<section class="v6box"><div class="v6title"><div><strong>Evolução do peso</strong><small>Inicial → atual → meta</small></div><div class="v6periods"><button class="v6period" data-d="7">7d</button><button class="v6period active" data-d="30">30d</button><button class="v6period" data-d="90">3m</button><button class="v6period" data-d="0">Tudo</button></div></div><div class="v6chart"><canvas id="v6WeightChart"></canvas></div></section>';
    h?h.insertAdjacentElement("afterend",x):a.prepend(x);
    $("v6LumaRefresh").onclick=function(){luma(true)};$("v6LumaOpen").onclick=function(){open("ia")};
    x.querySelectorAll("[data-a]").forEach(function(b){b.onclick=function(){action(b.dataset.a)}});x.querySelectorAll("[data-d]").forEach(function(b){b.onclick=function(){weightDays=+b.dataset.d;x.querySelectorAll("[data-d]").forEach(function(q){q.classList.toggle("active",q===b)});weightChartRender()}})
  }
  function nav(){
    var m=$("floatingMenu");if(!m||m.dataset.v6)return;m.dataset.v6="1";
    var d=m.querySelector('[data-aba="dashboard"]'),di=m.querySelector('[data-aba="alimentacao"]'),he=m.querySelector('[data-aba="saude"]'),ex=m.querySelector('[data-aba="exercicio"]'),ia=m.querySelector('[data-aba="ia"]');
    if(d){d.querySelector("span").textContent="Início";d.querySelector("i").className="bi bi-house-heart"}if(di)di.querySelector("span").textContent="Diário";if(he)he.querySelector("span").textContent="Saúde";if(ia){ia.querySelector("span").textContent="Luma";ia.querySelector("i").className="bi bi-stars"}if(ex)ex.remove();
    var p=document.createElement("button");p.className="floating-item";p.dataset.aba="perfil";p.innerHTML='<i class="bi bi-person-circle"></i><span>Perfil</span>';p.onclick=function(){open("perfil")};m.appendChild(p);
    if(!oldTrocar&&typeof window.trocarAba==="function"){oldTrocar=window.trocarAba;window.trocarAba=function(id,btn){var pp=$("aba-perfil-v6");if(pp)pp.style.display="none";oldTrocar(id,btn);m.querySelectorAll(".floating-item").forEach(function(b){b.classList.toggle("active",b.dataset.aba===id)});if(id==="saude")setTimeout(moveHealth,120);if(id==="alimentacao")setTimeout(function(){selectedDate=$("dataAlimentacaoInput")&&$("dataAlimentacaoInput").value||iso(new Date());calRender();dayRender(selectedDate);mealCards()},100);if(id==="ia")setTimeout(lumaQuick,80)}}
  }
  function profile(){
    if($("aba-perfil-v6"))return;var app=document.querySelector(".app-container"),p=document.createElement("div");p.id="aba-perfil-v6";p.className="aba-conteudo";p.innerHTML=
    '<header><h1>Perfil</h1><p>Metas, lembretes, conta e integrações</p></header><section id="v6ProfileCore"></section>'+
    '<section class="v6box"><div class="v6title"><strong>Objetivo e aparência</strong><small>Preferências</small></div><div class="v6settings"><button data-p="goal"><span><i class="bi bi-bullseye"></i> Meta de peso</span><small id="v6PG">Definir</small></button><button data-p="theme"><span><i class="bi bi-moon-stars"></i> Tema</span><small>Claro / escuro</small></button><button data-p="weight"><span><i class="bi bi-speedometer2"></i> Registrar medidas</span><small>Peso e medidas</small></button></div></section>'+
    '<section class="v6box"><div class="v6title"><strong>Lembretes</strong><small>Somente os que você ativar</small></div><div id="v6Reminder"></div></section>'+
    '<section class="v6box"><div class="v6title"><strong>Dados e integrações</strong><small>Área técnica</small></div><div class="v6settings"><button data-p="refresh"><span><i class="bi bi-arrow-clockwise"></i> Atualizar Health Connect</span><small>Sincronizar</small></button><button data-p="perm"><span><i class="bi bi-shield-check"></i> Permissões de saúde</span><small>Samsung Health</small></button><button data-p="diag"><span><i class="bi bi-wrench-adjustable"></i> Diagnóstico</span><small>Uso técnico</small></button><button data-p="account"><span><i class="bi bi-cloud-check"></i> Conta e backup</span><small>Nuvem</small></button></div></section><div id="v6AccountHost"></div>';
    app.insertBefore(p,$("floatingNav"));p.querySelectorAll("[data-p]").forEach(function(b){b.onclick=function(){profileAction(b.dataset.p)}});moveProfile()
  }
  function moveProfile(){
    var core=$("v6ProfileCore"),card=document.querySelector("#aba-ia .card-perfil-luma");if(core&&card&&!core.contains(card))core.appendChild(card);
    var rem=document.querySelector("#aba-saude .card-lembretes-luma"),rh=$("v6Reminder");if(rem&&rh&&!rh.contains(rem))rh.appendChild(rem);
    var cloud=$("cloudCardEvoluaFit"),ah=$("v6AccountHost");if(cloud&&ah&&!ah.contains(cloud))ah.appendChild(cloud)
  }
  function open(id){
    if(id==="perfil"){["aba-dashboard","aba-alimentacao","aba-saude","aba-exercicio","aba-ia"].forEach(function(x){if($(x))$(x).style.display="none"});$("aba-perfil-v6").style.display="block";document.querySelectorAll(".floating-item").forEach(function(b){b.classList.toggle("active",b.dataset.aba==="perfil")});moveProfile();profileUpdate();scrollTo(0,0);return}
    if(typeof window.trocarAba==="function")window.trocarAba(id,document.querySelector('.floating-item[data-aba="'+id+'"]'));scrollTo(0,0)
  }
  function action(a){if(a==="weight")weightSheet();else if(a==="meal")open("alimentacao");else if(a==="health")open("saude");else if(a==="workout"){if(oldTrocar)oldTrocar("exercicio",null);else if(typeof window.trocarAba==="function")window.trocarAba("exercicio")}}
  function profileAction(a){if(a==="goal"){goalSheet()}else if(a==="theme"){$("btnTema")&&$("btnTema").click()}else if(a==="weight")weightSheet();else if(a==="refresh"){$("hcRefreshBtn")&&$("hcRefreshBtn").click()}else if(a==="perm"){$("hcSettingsBtn")&&$("hcSettingsBtn").click()}else if(a==="diag"){open("saude");setTimeout(function(){var c=$("healthConnectCard");if(c)c.classList.add("tech");$("hcDiagnosticBtn")&&$("hcDiagnosticBtn").click()},150)}else if(a==="account"){var h=$("v6AccountHost");h&&h.scrollIntoView({behavior:"smooth"})}}
  function profileUpdate(){var g=n(localStorage.getItem("usuarioMeta"));if($("v6PG"))$("v6PG").textContent=g!=null?g.toFixed(1)+" kg":"Definir"}
  function homeUpdate(){
    if(!$("v6home"))return;var a=weights(),cur=a.length?a[a.length-1].v:null,start=a.length?a[0].v:null,goal=n(localStorage.getItem("usuarioMeta")),lost=cur!=null&&start!=null?start-cur:null,rem=cur!=null&&goal!=null?cur-goal:null;
    $("v6Weight").innerHTML=cur!=null?cur.toFixed(1)+' <small>kg</small>':'— <small>kg</small>';$("v6Goal").textContent=goal!=null?goal.toFixed(1)+" kg":"— kg";$("v6Start").textContent=start!=null?"Início "+start.toFixed(1)+" kg":"Início —";$("v6Lost").textContent=lost!=null?(lost>=0?"−"+Math.abs(lost).toFixed(1)+" kg":"+"+Math.abs(lost).toFixed(1)+" kg"):"Evolução —";$("v6Remain").textContent=rem!=null?(rem>0?"Faltam "+rem.toFixed(1)+" kg":rem===0?"Meta atingida":"Além da meta"):"Defina sua meta";var prog=0;if(start!=null&&cur!=null&&goal!=null&&start!==goal)prog=(start-cur)/(start-goal)*100;$("v6Prog").style.width=Math.max(0,Math.min(100,prog))+"%";$("v6Date").textContent=new Date().toLocaleDateString("pt-BR",{day:"2-digit",month:"short"});
    var d=j("historicoAlimentacao",{})[iso(new Date())]||{},k=n(d&&d.kcal&&typeof d.kcal==="object"?d.kcal.total:d.kcal),hc=j("evoluafitHealthConnectSnapshot",{})||{};$("v6Kcal").textContent=k!=null?Math.round(k)+" kcal":"—";$("v6Steps").textContent=n(hc.steps)!=null?Number(hc.steps).toLocaleString("pt-BR"):"—";$("v6Sleep").textContent=n(hc.sleepMinutes)!=null?dur(hc.sleepMinutes):"—";$("v6Heart").textContent=n(hc.heartRateAvg)!=null?Math.round(hc.heartRateAvg)+" bpm":"—";profileUpdate();lumaCache();weightChartRender()
  }
  function weightChartRender(){
    var c=$("v6WeightChart");if(!c||typeof Chart==="undefined")return;var a=weights();if(weightDays){var st=new Date();st.setHours(0,0,0,0);st.setDate(st.getDate()-(weightDays-1));a=a.filter(function(x){return x.d>=st})}if(weightChart)weightChart.destroy();var goal=n(localStorage.getItem("usuarioMeta")),sets=[{label:"Peso",data:a.map(function(x){return x.v}),borderColor:"#38bdf8",backgroundColor:"rgba(56,189,248,.09)",borderWidth:1.6,pointRadius:2.2,pointHoverRadius:5,tension:.34,fill:true}];if(goal!=null&&a.length)sets.push({label:"Meta",data:a.map(function(){return goal}),borderColor:"rgba(16,185,129,.8)",borderDash:[4,4],borderWidth:1,pointRadius:0});weightChart=new Chart(c,{type:"line",data:{labels:a.map(function(x){return x.d.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"})}),datasets:sets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{font:{size:9},maxTicksLimit:6}},y:{ticks:{font:{size:9},callback:function(v){return Number(v).toFixed(1)}},grid:{color:"rgba(148,163,184,.12)"}}}}})
  }
  function localSummary(){var hc=j("evoluafitHealthConnectSnapshot",{})||{},d=j("historicoAlimentacao",{})[iso(new Date())]||{},p=[];if(n(hc.sleepMinutes)!=null)p.push("Sono: "+dur(hc.sleepMinutes)+".");if(n(hc.steps)!=null)p.push(Number(hc.steps).toLocaleString("pt-BR")+" passos.");var k=n(d&&d.kcal&&typeof d.kcal==="object"?d.kcal.total:d.kcal);if(k!=null&&k>0)p.push(Math.round(k)+" kcal estimadas no diário.");if(!p.length)return "Ainda há poucos dados hoje. Registre peso, alimentação ou sincronize o Health Connect.";return p.slice(0,3).join(" ")}
  function lumaCache(){if(!$("v6Luma"))return;var c=j("iaAnaliseCache",null);$("v6Luma").textContent=c&&c.data===new Date().toLocaleDateString("pt-BR")?(String(c.dica||c.plano||localSummary()).replace(/\n+/g," ").slice(0,360)):localSummary()}
  async function luma(manual){var b=$("v6LumaRefresh"),e=$("v6Luma");if(b){b.disabled=true;b.textContent="Analisando…"}try{var data=typeof window.montarDadosParaIA==="function"?window.montarDadosParaIA():{dataHoje:iso(new Date()),perfilUsuario:j("usuarioPerfil",{}),historicoPeso:j("historicoPeso",[]).slice(-10),diarioHoje:j("historicoAlimentacao",{})[iso(new Date())]||null,ultimosTreinos:j("historicoTreinos",[]).slice(-5),healthConnect:j("evoluafitHealthConnectSnapshot",null)};var r=await fetch(API+"/analisar-dia",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!r.ok)throw Error("HTTP "+r.status);var o=await r.json(),t=String(o.resposta||""),q=t.split("DICA:"),cache={data:new Date().toLocaleDateString("pt-BR"),plano:(q[0]||"").replace(/^PLANO:\s*/,"").trim(),dica:(q[1]||"").trim()};localStorage.setItem("iaAnaliseCache",JSON.stringify(cache));lumaCache()}catch(err){console.warn("[V6] Luma",err);e.textContent=localSummary()+(manual?" A Luma online não respondeu agora.":"")}finally{if(b){b.disabled=false;b.textContent="Atualizar resumo"}}}
  function autoLuma(){var key=iso(new Date()),cache=j("iaAnaliseCache",null);if(localStorage.getItem("v6AutoLuma")===key||(cache&&cache.data===new Date().toLocaleDateString("pt-BR")))return;var has=weights().length||j("evoluafitHealthConnectSnapshot",null)||j("historicoAlimentacao",{})[key];if(has){localStorage.setItem("v6AutoLuma",key);setTimeout(function(){luma(false)},3500)}}
  function lumaQuick(){var a=$("aba-ia");if(!a||$("v6LQ"))return;var c=document.createElement("section");c.id="v6LQ";c.className="v6box";c.innerHTML='<div class="v6title"><strong>Atalhos da Luma</strong><small>Escolha uma leitura</small></div><div class="v6lq"><button data-lq="day"><i class="bi bi-stars"></i>Analisar meu dia</button><button data-lq="sleep"><i class="bi bi-moon-stars"></i>Como dormi?</button><button data-lq="food"><i class="bi bi-egg-fried"></i>Alimentação</button><button data-lq="progress"><i class="bi bi-graph-up-arrow"></i>Progresso</button><button data-lq="workout"><i class="bi bi-activity"></i>Montar treino</button></div>';var h=a.querySelector("header");h?h.insertAdjacentElement("afterend",c):a.prepend(c);c.querySelectorAll("[data-lq]").forEach(function(b){b.onclick=function(){var x=b.dataset.lq;if(x==="day")$("btnAnalisarDia")&&$("btnAnalisarDia").click();else if(x==="sleep"){open("saude");setTimeout(function(){var z=document.querySelector('[data-hc-detail="sleep"]');z&&z.click()},220)}else if(x==="food")open("alimentacao");else if(x==="progress")open("dashboard");else if(x==="workout"){if(oldTrocar)oldTrocar("exercicio",null);setTimeout(function(){$("btnGerarTreinoIA")&&$("btnGerarTreinoIA").click()},180)}}})}
  function healthHub(){var a=$("aba-saude");if(!a||$("v6HealthHub"))return;var c=document.createElement("section");c.id="v6HealthHub";c.className="v6box";c.innerHTML='<div class="v6healthhead"><div><strong>Saúde conectada</strong><div style="font-size:9px;color:var(--text-muted)">Samsung Health / Health Connect</div></div><i class="bi bi-heart-pulse" style="color:#0ea5e9;font-size:20px"></i></div><div id="v6HealthHost">Aguardando dados…</div><button id="v6Tech" class="v6tech">Dados e integrações</button>';var h=a.querySelector("header");h?h.insertAdjacentElement("afterend",c):a.prepend(c);$("v6Tech").onclick=function(){var x=$("healthConnectCard");if(x)x.classList.toggle("tech")};moveHealth()}
  function moveHealth(){var h=$("v6HealthHost"),c=$("healthConnectCard");if(h&&c&&!h.contains(c)){h.innerHTML="";h.appendChild(c)}}
  function calendar(){var a=$("aba-alimentacao");if(!a||$("v6Cal"))return;var c=document.createElement("section");c.id="v6Cal";c.className="v6cal";c.innerHTML='<div class="v6calh"><div><strong id="v6Month">Histórico diário</strong><div style="font-size:9px;color:var(--text-muted)">Toque em um dia para rever</div></div><div class="v6calnav"><button id="v6Prev">‹</button><button id="v6Next">›</button></div></div><div class="v6week"><span>D</span><span>S</span><span>T</span><span>Q</span><span>Q</span><span>S</span><span>S</span></div><div id="v6Days" class="v6days"></div><div id="v6DaySummary" class="v6summary"></div>';var h=a.querySelector("header");h?h.insertAdjacentElement("afterend",c):a.prepend(c);$("v6Prev").onclick=function(){calCursor=new Date(calCursor.getFullYear(),calCursor.getMonth()-1,1);calRender()};$("v6Next").onclick=function(){calCursor=new Date(calCursor.getFullYear(),calCursor.getMonth()+1,1);calRender()};var inp=$("dataAlimentacaoInput");if(inp)inp.addEventListener("change",function(){selectedDate=inp.value||iso(new Date());var d=pd(selectedDate);if(d)calCursor=new Date(d.getFullYear(),d.getMonth(),1);calRender();dayRender(selectedDate);setTimeout(mealCards,50)});calRender();dayRender(selectedDate)}
  function dataDates(){var s=new Set(),food=j("historicoAlimentacao",{});Object.keys(food||{}).forEach(function(k){s.add(k)});weights().forEach(function(x){s.add(iso(x.d))});[j("historicoTreinos",[]),j("historicoSaude",[])].forEach(function(a){if(Array.isArray(a))a.forEach(function(x){var d=itemDate(x);if(d)s.add(iso(d))})});return s}
  function calRender(){var g=$("v6Days");if(!g)return;var y=calCursor.getFullYear(),m=calCursor.getMonth();$("v6Month").textContent=new Date(y,m,1).toLocaleDateString("pt-BR",{month:"long",year:"numeric"});var f=new Date(y,m,1),st=new Date(y,m,1-f.getDay()),set=dataDates();g.innerHTML="";for(var i=0;i<42;i++){var d=new Date(st);d.setDate(st.getDate()+i);var k=iso(d),b=document.createElement("button");b.className="v6day";if(d.getMonth()!==m)b.classList.add("other");if(iso(new Date())===k)b.classList.add("today");if(selectedDate===k)b.classList.add("sel");if(set.has(k))b.classList.add("has");b.textContent=d.getDate();(function(key){b.onclick=function(){selectDate(key)}})(k);g.appendChild(b)}}
  function selectDate(k){selectedDate=k;var i=$("dataAlimentacaoInput");if(i){i.value=k;i.dispatchEvent(new Event("change",{bubbles:true}))}if(typeof window.carregarRefeicoesDoDia==="function")window.carregarRefeicoesDoDia();calRender();dayRender(k);setTimeout(mealCards,60)}
  async function dayRender(k){var h=$("v6DaySummary");if(!h)return;var d=j("historicoAlimentacao",{})[k]||{},w=weights().filter(function(x){return iso(x.d)===k}),wv=w.length?w[w.length-1].v:null,kcal=n(d&&d.kcal&&typeof d.kcal==="object"?d.kcal.total:d.kcal),water=n(d.agua),work=j("historicoTreinos",[]),wc=Array.isArray(work)?work.filter(function(x){var q=itemDate(x);return q&&iso(q)===k}).length:0,meals=MEALS.filter(function(x){return Array.isArray(d[x])&&d[x].length}).map(function(x){return LABELS[x]});h.innerHTML='<div class="v6title"><strong>'+esc(pd(k).toLocaleDateString("pt-BR",{weekday:"short",day:"2-digit",month:"2-digit"}))+'</strong><small id="v6HCS">Lendo saúde…</small></div><div class="v6sumgrid"><div class="v6sum"><span>Peso</span><strong>'+(wv!=null?wv.toFixed(1)+" kg":"—")+'</strong></div><div class="v6sum"><span>Calorias</span><strong>'+(kcal!=null?Math.round(kcal)+" kcal":"—")+'</strong></div><div class="v6sum"><span>Água</span><strong>'+(water!=null?Math.round(water)+" ml":"—")+'</strong></div><div class="v6sum"><span>Treinos</span><strong>'+wc+'</strong></div><div class="v6sum"><span>Passos</span><strong id="v6DS">—</strong></div><div class="v6sum"><span>Sono</span><strong id="v6DL">—</strong></div></div><div style="margin-top:8px;font-size:9px;color:var(--text-muted)">'+(meals.length?"Refeições: "+esc(meals.join(", ")):"Nenhuma refeição registrada.")+"</div>";var hc=await hcForDate(k);if(selectedDate!==k)return;if($("v6HCS"))$("v6HCS").textContent=hc?"Health Connect":"Sem dados conectados";if($("v6DS"))$("v6DS").textContent=hc&&n(hc.steps)!=null?Number(hc.steps).toLocaleString("pt-BR"):"—";if($("v6DL"))$("v6DL").textContent=hc&&n(hc.sleepMinutes)!=null?dur(hc.sleepMinutes):"—"}

  function mealAnalysis(m){try{if(typeof refeicoesAtuais!=="undefined"&&refeicoesAtuais.analisesFoto&&refeicoesAtuais.analisesFoto[m])return refeicoesAtuais.analisesFoto[m]}catch(_){}var d=j("historicoAlimentacao",{})[selectedDate]||{};return d.analisesFoto&&d.analisesFoto[m]||null}
  function mealCards(){MEALS.forEach(function(m){var input=$("custom-"+m),card=input&&input.closest(".meal-card");if(!card)return;var box=card.querySelector('[data-v6meal="'+m+'"]'),a=mealAnalysis(m);if(!a){if(box)box.remove();return}if(!box){box=document.createElement("div");box.className="v6meal";box.dataset.v6meal=m;input.parentElement.insertAdjacentElement("afterend",box)}var it=Array.isArray(a.itens)?a.itens:[];box.innerHTML='<div style="font-size:10px;line-height:1.45">'+(it.length?it.map(function(x){return "• "+esc(x.nome||"Alimento")+(x.quantidade?" · "+esc(x.quantidade):"")}).join("<br>"):"Análise salva")+'</div><div class="v6macros"><div class="v6macro"><span>Kcal</span><strong>'+Math.round(n(a.totalKcal)||0)+'</strong></div><div class="v6macro"><span>Proteína</span><strong>'+Math.round(n(a.proteinaG)||0)+'g</strong></div><div class="v6macro"><span>Carbo</span><strong>'+Math.round(n(a.carboidratosG)||0)+'g</strong></div><div class="v6macro"><span>Gordura</span><strong>'+Math.round(n(a.gordurasG)||0)+'g</strong></div></div><button>Corrigir análise</button><div style="clear:both"></div>';box.querySelector("button").onclick=function(){mealSheet(m,a)}})}
  function mealSheet(m,a){closeSheet();var s=document.createElement("div");s.id="v6Sheet";s.className="v6sheet";var it=Array.isArray(a.itens)?a.itens:[];s.innerHTML='<div class="v6sheetin"><div class="v6sheeth"><strong>Corrigir '+esc(LABELS[m])+'</strong><button class="v6close">×</button></div><div id="v6Edits">'+it.map(function(x){return '<div class="v6edit"><input data-f="nome" value="'+esc(x.nome||"")+'" placeholder="Alimento"><input data-f="quantidade" value="'+esc(x.quantidade||"")+'" placeholder="Porção"><input data-f="kcal" type="number" value="'+(n(x.kcal)||0)+'"></div>'}).join("")+'</div><button id="v6SaveMeal" class="v6save">Salvar correção</button></div>';document.body.appendChild(s);s.querySelector(".v6close").onclick=closeSheet;s.onclick=function(e){if(e.target===s)closeSheet()};$("v6SaveMeal").onclick=function(){saveMeal(m,a)}}
  function saveMeal(m,a){var rows=Array.from(document.querySelectorAll("#v6Edits .v6edit")),items=rows.map(function(r){function g(f){return (r.querySelector('[data-f="'+f+'"]')||{}).value||""}return{nome:g("nome").trim(),quantidade:g("quantidade").trim(),kcal:Math.max(0,n(g("kcal"))||0)}}).filter(function(x){return x.nome}),total=items.reduce(function(t,x){return t+x.kcal},0),u=Object.assign({},a,{itens:items,totalKcal:Math.round(total),corrigidoPeloUsuario:true,atualizadoEm:new Date().toISOString()});try{if(typeof refeicoesAtuais!=="undefined"){refeicoesAtuais.analisesFoto=refeicoesAtuais.analisesFoto||{};refeicoesAtuais.analisesFoto[m]=u;refeicoesAtuais[m]=items.map(function(x){return x.quantidade?x.nome+" ("+x.quantidade+")":x.nome});refeicoesAtuais.kcal=refeicoesAtuais.kcal||{cafe:0,almoco:0,jantar:0,ceia:0,total:0};refeicoesAtuais.kcal[m]=u.totalKcal;refeicoesAtuais.kcal.total=MEALS.reduce(function(t,q){return t+(n(refeicoesAtuais.kcal[q])||0)},0)}}catch(_){}var hist=j("historicoAlimentacao",{}),d=Object.assign({},hist[selectedDate]||{});d.analisesFoto=d.analisesFoto||{};d.analisesFoto[m]=u;d[m]=items.map(function(x){return x.quantidade?x.nome+" ("+x.quantidade+")":x.nome});d.kcal=d.kcal&&typeof d.kcal==="object"?d.kcal:{cafe:0,almoco:0,jantar:0,ceia:0,total:0};d.kcal[m]=u.totalKcal;d.kcal.total=MEALS.reduce(function(t,q){return t+(n(d.kcal[q])||0)},0);hist[selectedDate]=d;localStorage.setItem("historicoAlimentacao",JSON.stringify(hist));if(typeof window.renderizarTagsDeComida==="function")window.renderizarTagsDeComida();if(typeof window.renderizarCalorias==="function")window.renderizarCalorias();closeSheet();mealCards();dayRender(selectedDate);homeUpdate()}
  function goalSheet(){closeSheet();var s=document.createElement("div");s.id="v6Sheet";s.className="v6sheet";var g=n(localStorage.getItem("usuarioMeta"));s.innerHTML='<div class="v6sheetin"><div class="v6sheeth"><strong>Meta de peso</strong><button class="v6close">×</button></div><label style="font-size:9px;color:var(--text-muted);font-weight:800">Nova meta (kg)<input id="v6GoalInput" type="number" step="0.1" value="'+(g!=null?g:"")+'" placeholder="Ex: 75.0"></label><button id="v6GoalSave" class="v6save">Salvar meta</button></div>';document.body.appendChild(s);s.querySelector(".v6close").onclick=closeSheet;s.onclick=function(e){if(e.target===s)closeSheet()};$("v6GoalSave").onclick=function(){var v=n($("v6GoalInput").value);if(v==null||v<30||v>300){alert("Informe uma meta válida.");return}localStorage.setItem("usuarioMeta",String(v));if($("metaInput"))$("metaInput").value=v;if(typeof window.atualizarDashboard==="function")window.atualizarDashboard();closeSheet();homeUpdate();profileUpdate()}}
  async function hcForDate(k){if(k===iso(new Date()))return j("evoluafitHealthConnectSnapshot",null);try{var cap=window.Capacitor,health=cap&&cap.Plugins&&cap.Plugins.Health;if(!health)return null;var d=pd(k),st=new Date(d.getFullYear(),d.getMonth(),d.getDate()),en=new Date(d.getFullYear(),d.getMonth(),d.getDate()+1);var steps=null,sleep=null;if(health.queryAggregated){try{var r=await health.queryAggregated({dataType:"steps",startDate:st.toISOString(),endDate:en.toISOString(),bucket:"day",aggregation:"sum"}),a=r&&Array.isArray(r.samples)?r.samples:[];if(a.length)steps=Math.round(a.reduce(function(t,x){return t+Number(x.value||0)},0))}catch(_){}}if(health.readSamples){try{var q=await health.readSamples({dataType:"sleep",startDate:st.toISOString(),endDate:en.toISOString(),limit:50}),b=q&&Array.isArray(q.samples)?q.samples:[];if(b.length){b.sort(function(x,y){return new Date(y.endDate||y.startDate||0)-new Date(x.endDate||x.startDate||0)});sleep=n(b[0].value)}}catch(_){}}return steps!=null||sleep!=null?{steps:steps,sleepMinutes:sleep}:null}catch(_){return null}}
  function weightSheet(){closeSheet();var s=document.createElement("div");s.id="v6Sheet";s.className="v6sheet";s.innerHTML='<div class="v6sheetin"><div class="v6sheeth"><strong>Registrar medidas</strong><button class="v6close">×</button></div><div class="v6form"><label>Data<input id="v6WD" type="date" value="'+iso(new Date())+'"></label><label>Peso<input id="v6WV" type="number" step="0.1" placeholder="kg"></label><label>Cintura<input id="v6WC" type="number" step="0.1"></label><label>Quadril<input id="v6WH" type="number" step="0.1"></label></div><button id="v6WS" class="v6save">Salvar registro</button></div>';document.body.appendChild(s);s.querySelector(".v6close").onclick=closeSheet;s.onclick=function(e){if(e.target===s)closeSheet()};$("v6WS").onclick=function(){var v=n($("v6WV").value);if(v==null||v<20||v>400){alert("Informe um peso válido.");return}if($("dataInput"))$("dataInput").value=$("v6WD").value;if($("pesoInput"))$("pesoInput").value=v;if($("cinturaInput"))$("cinturaInput").value=$("v6WC").value;if($("quadrilInput"))$("quadrilInput").value=$("v6WH").value;$("btnSalvar")&&$("btnSalvar").click();closeSheet();setTimeout(homeUpdate,180)}}
  function closeSheet(){var s=$("v6Sheet");if(s)s.remove()}
  function observe(){if(observer)return;observer=new MutationObserver(function(){moveHealth();moveProfile();mealCards()});observer.observe(document.body,{subtree:true,childList:true});document.addEventListener("evoluafit:meal-analysis-updated",function(){mealCards();homeUpdate()});window.addEventListener("storage",function(){homeUpdate();calRender()})}
  function start(){if(!document.body)return;document.body.classList.add("evolua-v6");styles();home();profile();nav();healthHub();calendar();lumaQuick();moveHealth();moveProfile();mealCards();homeUpdate();autoLuma();observe();setInterval(function(){homeUpdate();moveHealth();moveProfile()},5000)}
  document.addEventListener("DOMContentLoaded",function(){setTimeout(start,700)});if(document.readyState!=="loading")setTimeout(start,700)
})();